//------------------------------------------------------------------------
//  D O     N O T     E D I T     T H I S     F I L E 
//------------------------------------------------------------------------
// File         :  cbpm_adc_buffer_get_a.c
// Date Created :  Fri Sep 14 14:08:01 2012
//
// Description  :  This file was automatically generated by the BIParser.
//                 It provides a standardized accessor function to allow
//                 retrieval of data values from a collection of identical
//                 data buffer structures, indexed in a 
//                 <card, timing_block, channel> fashion.
//------------------------------------------------------------------------
#include "cbpm_includes.h"

int cbpm_adc_buffer_get(CBPM_DATA *dp, int card, int tblock, int idx) { 

int buf_number = (card*CBPM_MAX_TIMING_BLOCKS*CBPM_MAX_CARD_ADCS_PER_BLOCK) +
                 (tblock*CBPM_MAX_CARD_ADCS_PER_BLOCK);
int *ptr;

switch (buf_number) {
case (0):
  ptr = (int*)&(dp->cbpm_adc_buffer0);
  return *(ptr+idx);
  break;
case (1):
  ptr = (int*)&(dp->cbpm_adc_buffer1);
  return *(ptr+idx);
  break;
case (2):
  ptr = (int*)&(dp->cbpm_adc_buffer2);
  return *(ptr+idx);
  break;
case (3):
  ptr = (int*)&(dp->cbpm_adc_buffer3);
  return *(ptr+idx);
  break;
case (4):
  ptr = (int*)&(dp->cbpm_adc_buffer4);
  return *(ptr+idx);
  break;
case (5):
  ptr = (int*)&(dp->cbpm_adc_buffer5);
  return *(ptr+idx);
  break;
case (6):
  ptr = (int*)&(dp->cbpm_adc_buffer6);
  return *(ptr+idx);
  break;
case (7):
  ptr = (int*)&(dp->cbpm_adc_buffer7);
  return *(ptr+idx);
  break;
  default:
      break;
  }
  return CBI_F_SUCCESS;
}
