
//------------------------------------------------------------------------
//  D O     N O T     E D I T     T H I S     F I L E
//------------------------------------------------------------------------
// File         :  cbpm_init_a.c
// Date Created :  Fri Sep 14 14:08:01 2012
//
// Description  :  This file was automatically generated by the BIParser.
//                 It initializes one instrument's worth of communication
//                 data structures for a particular platform.
//                 This routine is for CONTROL application usage only.
//------------------------------------------------------------------------

// ACC System Includes
#include "CESR_platform.h"
#include "utilities.h"

#define CBPM_NO_EXTERN

#include "cbi_core_includes.h"
#include "cbpm_config_a.h"




int cbpm_init_a(CBI_CTL_MODULE *p_ctl_mod) {
  int i, first_tag, num_tags, tag;
  COMM_KEY *p_key;

  CBI_DATA* p_core;
  p_core=p_ctl_mod->core;
  CBPM_DATA  data;
  CBPM_DATA* p_data;
  p_data=(CBPM_DATA*)(p_ctl_mod->dsp_data);


//---Initializations for cbpm_cmd_params
  p_key = &(p_ctl_mod->key[p_ctl_mod->n_keys]);
  // configuration
  p_key->p_config      = &(cbpm_cmd_params_cfg);
  //data pointers
  p_key->data.ptr[ 0]  = (void *)(&(p_data->cbpm_cmd_params.species));
  p_key->data.ptr[ 1]  = (void *)(&(p_data->cbpm_cmd_params.num_turns));
  p_key->data.ptr[ 2]  = (void *)(&(p_data->cbpm_cmd_params.bunch_pat[0]));
  p_key->data.ptr[ 3]  = (void *)(&(p_data->cbpm_cmd_params.rot_bunch_pat[0]));
  p_key->data.ptr[ 4]  = (void *)(&(p_data->cbpm_cmd_params.trig_turns_delay));
  p_key->data.ptr[ 5]  = (void *)(&(p_data->cbpm_cmd_params.spacex_turn));
  p_key->data.ptr[ 6]  = (void *)(&(p_data->cbpm_cmd_params.delay_cal));
  p_key->data.ptr[ 7]  = (void *)(&(p_data->cbpm_cmd_params.generate_delay_corrections));
  p_key->data.ptr[ 8]  = (void *)(&(p_data->cbpm_cmd_params.gain_cal));
  p_key->data.ptr[ 9]  = (void *)(&(p_data->cbpm_cmd_params.gain_xcal));
  p_key->data.ptr[10]  = (void *)(&(p_data->cbpm_cmd_params.avg_mode));
  p_key->data.ptr[11]  = (void *)(&(p_data->cbpm_cmd_params.scale_mode));
  p_key->data.ptr[12]  = (void *)(&(p_data->cbpm_cmd_params.update_mode));
  p_key->data.ptr[13]  = (void *)(&(p_data->cbpm_cmd_params.use_data_enable));
  p_key->data.ptr[14]  = (void *)(&(p_data->cbpm_cmd_params.trig_mask));
  p_key->data.ptr[15]  = (void *)(&(p_data->cbpm_cmd_params.reset_proc_buf_idx));
  p_key->data.ptr[16]  = (void *)(&(p_data->cbpm_cmd_params.generate_phase_tables));
  p_key->data.ptr[17]  = (void *)(&(p_data->cbpm_cmd_params.tblock));
  p_key->data.ptr[18]  = (void *)(&(p_data->cbpm_cmd_params.bun_pat_offset));
  p_key->data.ptr[19]  = (void *)(&(p_data->cbpm_cmd_params.checksum));
  // tag2key_map
  first_tag = p_key->p_config->struct_tag;
  num_tags  = p_key->p_config->num_pkts;
  for (tag = first_tag; tag < (first_tag + num_tags); tag++) {
    p_ctl_mod->tag2key_map[tag] = p_ctl_mod->n_keys;
  }
  p_ctl_mod->n_keys++;



//---Initializations for cbpm_temperatures
  p_key = &(p_ctl_mod->key[p_ctl_mod->n_keys]);
  // configuration
  p_key->p_config      = &(cbpm_temperatures_cfg);
  //data pointers
  p_key->data.ptr[ 0]  = (void *)(&(p_data->cbpm_temperatures.dig_temp));
  p_key->data.ptr[ 1]  = (void *)(&(p_data->cbpm_temperatures.tim_temp));
  p_key->data.ptr[ 2]  = (void *)(&(p_data->cbpm_temperatures.fe_temps[0]));
  // tag2key_map
  first_tag = p_key->p_config->struct_tag;
  num_tags  = p_key->p_config->num_pkts;
  for (tag = first_tag; tag < (first_tag + num_tags); tag++) {
    p_ctl_mod->tag2key_map[tag] = p_ctl_mod->n_keys;
  }
  p_ctl_mod->n_keys++;



//---Initializations for cbpm_timing_config
  p_key = &(p_ctl_mod->key[p_ctl_mod->n_keys]);
  // configuration
  p_key->p_config      = &(cbpm_timing_config_cfg);
  //data pointers
  p_key->data.ptr[ 0]  = (void *)(&(p_data->cbpm_timing_config.setups[0]));
  // tag2key_map
  first_tag = p_key->p_config->struct_tag;
  num_tags  = p_key->p_config->num_pkts;
  for (tag = first_tag; tag < (first_tag + num_tags); tag++) {
    p_ctl_mod->tag2key_map[tag] = p_ctl_mod->n_keys;
  }
  p_ctl_mod->n_keys++;



//---Initializations for cbpm_gain_config
  p_key = &(p_ctl_mod->key[p_ctl_mod->n_keys]);
  // configuration
  p_key->p_config      = &(cbpm_gain_config_cfg);
  //data pointers
  p_key->data.ptr[ 0]  = (void *)(&(p_data->cbpm_gain_config.gain_codes[0]));
  p_key->data.ptr[ 1]  = (void *)(&(p_data->cbpm_gain_config.gain_table[0][0][0]));
  p_key->data.ptr[ 2]  = (void *)(&(p_data->cbpm_gain_config.gain_err_table[0][0][0]));
  p_key->data.ptr[ 3]  = (void *)(&(p_data->cbpm_gain_config.chan_map[0]));
  // tag2key_map
  first_tag = p_key->p_config->struct_tag;
  num_tags  = p_key->p_config->num_pkts;
  for (tag = first_tag; tag < (first_tag + num_tags); tag++) {
    p_ctl_mod->tag2key_map[tag] = p_ctl_mod->n_keys;
  }
  p_ctl_mod->n_keys++;



//---Initializations for cbpm_pedestal_config
  p_key = &(p_ctl_mod->key[p_ctl_mod->n_keys]);
  // configuration
  p_key->p_config      = &(cbpm_pedestal_config_cfg);
  //data pointers
  p_key->data.ptr[ 0]  = (void *)(&(p_data->cbpm_pedestal_config.tables[0]));
  // tag2key_map
  first_tag = p_key->p_config->struct_tag;
  num_tags  = p_key->p_config->num_pkts;
  for (tag = first_tag; tag < (first_tag + num_tags); tag++) {
    p_ctl_mod->tag2key_map[tag] = p_ctl_mod->n_keys;
  }
  p_ctl_mod->n_keys++;



//---Initializations for cbpm_op_timing
  p_key = &(p_ctl_mod->key[p_ctl_mod->n_keys]);
  // configuration
  p_key->p_config      = &(cbpm_op_timing_cfg);
  //data pointers
  p_key->data.ptr[ 0]  = (void *)(&(p_data->cbpm_op_timing.active_timing_setup));
  // tag2key_map
  first_tag = p_key->p_config->struct_tag;
  num_tags  = p_key->p_config->num_pkts;
  for (tag = first_tag; tag < (first_tag + num_tags); tag++) {
    p_ctl_mod->tag2key_map[tag] = p_ctl_mod->n_keys;
  }
  p_ctl_mod->n_keys++;



//---Initializations for cbpm_op_gain
  p_key = &(p_ctl_mod->key[p_ctl_mod->n_keys]);
  // configuration
  p_key->p_config      = &(cbpm_op_gain_cfg);
  //data pointers
  p_key->data.ptr[ 0]  = (void *)(&(p_data->cbpm_op_gain.active_gain_settings[0][0]));
  // tag2key_map
  first_tag = p_key->p_config->struct_tag;
  num_tags  = p_key->p_config->num_pkts;
  for (tag = first_tag; tag < (first_tag + num_tags); tag++) {
    p_ctl_mod->tag2key_map[tag] = p_ctl_mod->n_keys;
  }
  p_ctl_mod->n_keys++;



//---Initializations for cbpm_raw_data_header
  p_key = &(p_ctl_mod->key[p_ctl_mod->n_keys]);
  // configuration
  p_key->p_config      = &(cbpm_raw_data_header_cfg);
  //data pointers
  p_key->data.ptr[ 0]  = (void *)(&(p_data->cbpm_raw_data_header.tot_bunches));
  p_key->data.ptr[ 1]  = (void *)(&(p_data->cbpm_raw_data_header.num_bunches[0]));
  p_key->data.ptr[ 2]  = (void *)(&(p_data->cbpm_raw_data_header.num_BP_bits_wrapped[0]));
  p_key->data.ptr[ 3]  = (void *)(&(p_data->cbpm_raw_data_header.num_turns));
  p_key->data.ptr[ 4]  = (void *)(&(p_data->cbpm_raw_data_header.skip_turns_active));
  p_key->data.ptr[ 5]  = (void *)(&(p_data->cbpm_raw_data_header.turn_counter));
  p_key->data.ptr[ 6]  = (void *)(&(p_data->cbpm_raw_data_header.trig_turns_delay));
  p_key->data.ptr[ 7]  = (void *)(&(p_data->cbpm_raw_data_header.spacex_turn));
  p_key->data.ptr[ 8]  = (void *)(&(p_data->cbpm_raw_data_header.scale_mode));
  p_key->data.ptr[ 9]  = (void *)(&(p_data->cbpm_raw_data_header.ADC_zero_val_bitfields[0]));
  p_key->data.ptr[10]  = (void *)(&(p_data->cbpm_raw_data_header.ADC_lower_thresh_bitfields[0]));
  p_key->data.ptr[11]  = (void *)(&(p_data->cbpm_raw_data_header.ADC_low_thresh_bitfields[0]));
  p_key->data.ptr[12]  = (void *)(&(p_data->cbpm_raw_data_header.ADC_high_thresh_bitfields[0]));
  p_key->data.ptr[13]  = (void *)(&(p_data->cbpm_raw_data_header.ADC_saturation_bitfields[0]));
  p_key->data.ptr[14]  = (void *)(&(p_data->cbpm_raw_data_header.gain[0][0]));
  // tag2key_map
  first_tag = p_key->p_config->struct_tag;
  num_tags  = p_key->p_config->num_pkts;
  for (tag = first_tag; tag < (first_tag + num_tags); tag++) {
    p_ctl_mod->tag2key_map[tag] = p_ctl_mod->n_keys;
  }
  p_ctl_mod->n_keys++;



//---Initializations for cbpm_adc_buffer0
  p_key = &(p_ctl_mod->key[p_ctl_mod->n_keys]);
  // configuration
  p_key->p_config      = &(cbpm_adc_buffer0_cfg);
  //data pointers
  p_key->data.ptr[ 0]  = (void *)(&(p_data->cbpm_adc_buffer0.raw_data[0]));
  // tag2key_map
  first_tag = p_key->p_config->struct_tag;
  num_tags  = p_key->p_config->num_pkts;
  for (tag = first_tag; tag < (first_tag + num_tags); tag++) {
    p_ctl_mod->tag2key_map[tag] = p_ctl_mod->n_keys;
  }
  p_ctl_mod->n_keys++;



//---Initializations for cbpm_adc_buffer1
  p_key = &(p_ctl_mod->key[p_ctl_mod->n_keys]);
  // configuration
  p_key->p_config      = &(cbpm_adc_buffer1_cfg);
  //data pointers
  p_key->data.ptr[ 0]  = (void *)(&(p_data->cbpm_adc_buffer1.raw_data[0]));
  // tag2key_map
  first_tag = p_key->p_config->struct_tag;
  num_tags  = p_key->p_config->num_pkts;
  for (tag = first_tag; tag < (first_tag + num_tags); tag++) {
    p_ctl_mod->tag2key_map[tag] = p_ctl_mod->n_keys;
  }
  p_ctl_mod->n_keys++;



//---Initializations for cbpm_adc_buffer2
  p_key = &(p_ctl_mod->key[p_ctl_mod->n_keys]);
  // configuration
  p_key->p_config      = &(cbpm_adc_buffer2_cfg);
  //data pointers
  p_key->data.ptr[ 0]  = (void *)(&(p_data->cbpm_adc_buffer2.raw_data[0]));
  // tag2key_map
  first_tag = p_key->p_config->struct_tag;
  num_tags  = p_key->p_config->num_pkts;
  for (tag = first_tag; tag < (first_tag + num_tags); tag++) {
    p_ctl_mod->tag2key_map[tag] = p_ctl_mod->n_keys;
  }
  p_ctl_mod->n_keys++;



//---Initializations for cbpm_adc_buffer3
  p_key = &(p_ctl_mod->key[p_ctl_mod->n_keys]);
  // configuration
  p_key->p_config      = &(cbpm_adc_buffer3_cfg);
  //data pointers
  p_key->data.ptr[ 0]  = (void *)(&(p_data->cbpm_adc_buffer3.raw_data[0]));
  // tag2key_map
  first_tag = p_key->p_config->struct_tag;
  num_tags  = p_key->p_config->num_pkts;
  for (tag = first_tag; tag < (first_tag + num_tags); tag++) {
    p_ctl_mod->tag2key_map[tag] = p_ctl_mod->n_keys;
  }
  p_ctl_mod->n_keys++;



//---Initializations for cbpm_adc_buffer4
  p_key = &(p_ctl_mod->key[p_ctl_mod->n_keys]);
  // configuration
  p_key->p_config      = &(cbpm_adc_buffer4_cfg);
  //data pointers
  p_key->data.ptr[ 0]  = (void *)(&(p_data->cbpm_adc_buffer4.raw_data[0]));
  // tag2key_map
  first_tag = p_key->p_config->struct_tag;
  num_tags  = p_key->p_config->num_pkts;
  for (tag = first_tag; tag < (first_tag + num_tags); tag++) {
    p_ctl_mod->tag2key_map[tag] = p_ctl_mod->n_keys;
  }
  p_ctl_mod->n_keys++;



//---Initializations for cbpm_adc_buffer5
  p_key = &(p_ctl_mod->key[p_ctl_mod->n_keys]);
  // configuration
  p_key->p_config      = &(cbpm_adc_buffer5_cfg);
  //data pointers
  p_key->data.ptr[ 0]  = (void *)(&(p_data->cbpm_adc_buffer5.raw_data[0]));
  // tag2key_map
  first_tag = p_key->p_config->struct_tag;
  num_tags  = p_key->p_config->num_pkts;
  for (tag = first_tag; tag < (first_tag + num_tags); tag++) {
    p_ctl_mod->tag2key_map[tag] = p_ctl_mod->n_keys;
  }
  p_ctl_mod->n_keys++;



//---Initializations for cbpm_adc_buffer6
  p_key = &(p_ctl_mod->key[p_ctl_mod->n_keys]);
  // configuration
  p_key->p_config      = &(cbpm_adc_buffer6_cfg);
  //data pointers
  p_key->data.ptr[ 0]  = (void *)(&(p_data->cbpm_adc_buffer6.raw_data[0]));
  // tag2key_map
  first_tag = p_key->p_config->struct_tag;
  num_tags  = p_key->p_config->num_pkts;
  for (tag = first_tag; tag < (first_tag + num_tags); tag++) {
    p_ctl_mod->tag2key_map[tag] = p_ctl_mod->n_keys;
  }
  p_ctl_mod->n_keys++;



//---Initializations for cbpm_adc_buffer7
  p_key = &(p_ctl_mod->key[p_ctl_mod->n_keys]);
  // configuration
  p_key->p_config      = &(cbpm_adc_buffer7_cfg);
  //data pointers
  p_key->data.ptr[ 0]  = (void *)(&(p_data->cbpm_adc_buffer7.raw_data[0]));
  // tag2key_map
  first_tag = p_key->p_config->struct_tag;
  num_tags  = p_key->p_config->num_pkts;
  for (tag = first_tag; tag < (first_tag + num_tags); tag++) {
    p_ctl_mod->tag2key_map[tag] = p_ctl_mod->n_keys;
  }
  p_ctl_mod->n_keys++;



//---Initializations for cbpm_ph_word_buf
  p_key = &(p_ctl_mod->key[p_ctl_mod->n_keys]);
  // configuration
  p_key->p_config      = &(cbpm_ph_word_buf_cfg);
  //data pointers
  p_key->data.ptr[ 0]  = (void *)(&(p_data->cbpm_ph_word_buf.ph_words[0]));
  // tag2key_map
  first_tag = p_key->p_config->struct_tag;
  num_tags  = p_key->p_config->num_pkts;
  for (tag = first_tag; tag < (first_tag + num_tags); tag++) {
    p_ctl_mod->tag2key_map[tag] = p_ctl_mod->n_keys;
  }
  p_ctl_mod->n_keys++;



//---Initializations for cbpm_proc_buf
  p_key = &(p_ctl_mod->key[p_ctl_mod->n_keys]);
  // configuration
  p_key->p_config      = &(cbpm_proc_buf_cfg);
  //data pointers
  p_key->data.ptr[ 0]  = (void *)(&(p_data->cbpm_proc_buf.proc_data[0]));
  // tag2key_map
  first_tag = p_key->p_config->struct_tag;
  num_tags  = p_key->p_config->num_pkts;
  for (tag = first_tag; tag < (first_tag + num_tags); tag++) {
    p_ctl_mod->tag2key_map[tag] = p_ctl_mod->n_keys;
  }
  p_ctl_mod->n_keys++;



//---Initializations for cbpm_proc_buf_header
  p_key = &(p_ctl_mod->key[p_ctl_mod->n_keys]);
  // configuration
  p_key->p_config      = &(cbpm_proc_buf_header_cfg);
  //data pointers
  p_key->data.ptr[ 0]  = (void *)(&(p_data->cbpm_proc_buf_header.species));
  p_key->data.ptr[ 1]  = (void *)(&(p_data->cbpm_proc_buf_header.write_ptr[0]));
  p_key->data.ptr[ 2]  = (void *)(&(p_data->cbpm_proc_buf_header.active_buf));
  // tag2key_map
  first_tag = p_key->p_config->struct_tag;
  num_tags  = p_key->p_config->num_pkts;
  for (tag = first_tag; tag < (first_tag + num_tags); tag++) {
    p_ctl_mod->tag2key_map[tag] = p_ctl_mod->n_keys;
  }
  p_ctl_mod->n_keys++;



//---Initializations for cbpm_proc_sum_dat_buf
  p_key = &(p_ctl_mod->key[p_ctl_mod->n_keys]);
  // configuration
  p_key->p_config      = &(cbpm_proc_sum_dat_buf_cfg);
  //data pointers
  p_key->data.ptr[ 0]  = (void *)(&(p_data->cbpm_proc_sum_dat_buf.signal_sum[0]));
  p_key->data.ptr[ 1]  = (void *)(&(p_data->cbpm_proc_sum_dat_buf.fill_count));
  p_key->data.ptr[ 2]  = (void *)(&(p_data->cbpm_proc_sum_dat_buf.gain_values[0][0]));
  // tag2key_map
  first_tag = p_key->p_config->struct_tag;
  num_tags  = p_key->p_config->num_pkts;
  for (tag = first_tag; tag < (first_tag + num_tags); tag++) {
    p_ctl_mod->tag2key_map[tag] = p_ctl_mod->n_keys;
  }
  p_ctl_mod->n_keys++;



//---Initializations for cbpm_proc_buf_io
  p_key = &(p_ctl_mod->key[p_ctl_mod->n_keys]);
  // configuration
  p_key->p_config      = &(cbpm_proc_buf_io_cfg);
  //data pointers
  p_key->data.ptr[ 0]  = (void *)(&(p_data->cbpm_proc_buf_io.handshake));
  // tag2key_map
  first_tag = p_key->p_config->struct_tag;
  num_tags  = p_key->p_config->num_pkts;
  for (tag = first_tag; tag < (first_tag + num_tags); tag++) {
    p_ctl_mod->tag2key_map[tag] = p_ctl_mod->n_keys;
  }
  p_ctl_mod->n_keys++;



//---Initializations for cbpm_summ_buf
  p_key = &(p_ctl_mod->key[p_ctl_mod->n_keys]);
  // configuration
  p_key->p_config      = &(cbpm_summ_buf_cfg);
  //data pointers
  p_key->data.ptr[ 0]  = (void *)(&(p_data->cbpm_summ_buf.data[0]));
  // tag2key_map
  first_tag = p_key->p_config->struct_tag;
  num_tags  = p_key->p_config->num_pkts;
  for (tag = first_tag; tag < (first_tag + num_tags); tag++) {
    p_ctl_mod->tag2key_map[tag] = p_ctl_mod->n_keys;
  }
  p_ctl_mod->n_keys++;



//---Initializations for cbpm_signal_stat
  p_key = &(p_ctl_mod->key[p_ctl_mod->n_keys]);
  // configuration
  p_key->p_config      = &(cbpm_signal_stat_cfg);
  //data pointers
  p_key->data.ptr[ 0]  = (void *)(&(p_data->cbpm_signal_stat.signal_avg[0]));
  p_key->data.ptr[ 1]  = (void *)(&(p_data->cbpm_signal_stat.signal_rms[0]));
  // tag2key_map
  first_tag = p_key->p_config->struct_tag;
  num_tags  = p_key->p_config->num_pkts;
  for (tag = first_tag; tag < (first_tag + num_tags); tag++) {
    p_ctl_mod->tag2key_map[tag] = p_ctl_mod->n_keys;
  }
  p_ctl_mod->n_keys++;



//---Initializations for cbpm_phase_config
  p_key = &(p_ctl_mod->key[p_ctl_mod->n_keys]);
  // configuration
  p_key->p_config      = &(cbpm_phase_config_cfg);
  //data pointers
  p_key->data.ptr[ 0]  = (void *)(&(p_data->cbpm_phase_config.phase_jump_boundaries[0][0]));
  p_key->data.ptr[ 1]  = (void *)(&(p_data->cbpm_phase_config.phase_turn_offsets[0][0]));
  p_key->data.ptr[ 2]  = (void *)(&(p_data->cbpm_phase_config.phase_wait_values[0][0]));
  // tag2key_map
  first_tag = p_key->p_config->struct_tag;
  num_tags  = p_key->p_config->num_pkts;
  for (tag = first_tag; tag < (first_tag + num_tags); tag++) {
    p_ctl_mod->tag2key_map[tag] = p_ctl_mod->n_keys;
  }
  p_ctl_mod->n_keys++;



//---Initializations for cbpm_beta_phase_out
  p_key = &(p_ctl_mod->key[p_ctl_mod->n_keys]);
  // configuration
  p_key->p_config      = &(cbpm_beta_phase_out_cfg);
  //data pointers
  p_key->data.ptr[ 0]  = (void *)(&(p_data->cbpm_beta_phase_out.bunch_id));
  p_key->data.ptr[ 1]  = (void *)(&(p_data->cbpm_beta_phase_out.tot_turns));
  p_key->data.ptr[ 2]  = (void *)(&(p_data->cbpm_beta_phase_out.turn_ctr_offset));
  p_key->data.ptr[ 3]  = (void *)(&(p_data->cbpm_beta_phase_out.phase_results[0][0][0][0][0]));
  p_key->data.ptr[ 4]  = (void *)(&(p_data->cbpm_beta_phase_out.signal[0]));
  // tag2key_map
  first_tag = p_key->p_config->struct_tag;
  num_tags  = p_key->p_config->num_pkts;
  for (tag = first_tag; tag < (first_tag + num_tags); tag++) {
    p_ctl_mod->tag2key_map[tag] = p_ctl_mod->n_keys;
  }
  p_ctl_mod->n_keys++;



//---Initializations for cbpm_find_delay_out
  p_key = &(p_ctl_mod->key[p_ctl_mod->n_keys]);
  // configuration
  p_key->p_config      = &(cbpm_find_delay_out_cfg);
  //data pointers
  p_key->data.ptr[ 0]  = (void *)(&(p_data->cbpm_find_delay_out.max_block_delay));
  p_key->data.ptr[ 1]  = (void *)(&(p_data->cbpm_find_delay_out.fcoeffs[0]));
  p_key->data.ptr[ 2]  = (void *)(&(p_data->cbpm_find_delay_out.peaks[0]));
  p_key->data.ptr[ 3]  = (void *)(&(p_data->cbpm_find_delay_out.offsets[0]));
  p_key->data.ptr[ 4]  = (void *)(&(p_data->cbpm_find_delay_out.prevADCRMSs[0]));
  p_key->data.ptr[ 5]  = (void *)(&(p_data->cbpm_find_delay_out.postADCRMSs[0]));
  p_key->data.ptr[ 6]  = (void *)(&(p_data->cbpm_find_delay_out.num_retries));
  p_key->data.ptr[ 7]  = (void *)(&(p_data->cbpm_find_delay_out.numTurnsToCollectPeakData));
  // tag2key_map
  first_tag = p_key->p_config->struct_tag;
  num_tags  = p_key->p_config->num_pkts;
  for (tag = first_tag; tag < (first_tag + num_tags); tag++) {
    p_ctl_mod->tag2key_map[tag] = p_ctl_mod->n_keys;
  }
  p_ctl_mod->n_keys++;



//---Initializations for cbpm_bfind_delay_out
  p_key = &(p_ctl_mod->key[p_ctl_mod->n_keys]);
  // configuration
  p_key->p_config      = &(cbpm_bfind_delay_out_cfg);
  //data pointers
  p_key->data.ptr[ 0]  = (void *)(&(p_data->cbpm_bfind_delay_out.offsetshist[0][0]));
  p_key->data.ptr[ 1]  = (void *)(&(p_data->cbpm_bfind_delay_out.peakshist[0][0]));
  p_key->data.ptr[ 2]  = (void *)(&(p_data->cbpm_bfind_delay_out.chipshist[0][0]));
  p_key->data.ptr[ 3]  = (void *)(&(p_data->cbpm_bfind_delay_out.blockhist[0]));
  p_key->data.ptr[ 4]  = (void *)(&(p_data->cbpm_bfind_delay_out.timingUpdateIsGoodhist[0]));
  p_key->data.ptr[ 5]  = (void *)(&(p_data->cbpm_bfind_delay_out.rollbackhist[0]));
  // tag2key_map
  first_tag = p_key->p_config->struct_tag;
  num_tags  = p_key->p_config->num_pkts;
  for (tag = first_tag; tag < (first_tag + num_tags); tag++) {
    p_ctl_mod->tag2key_map[tag] = p_ctl_mod->n_keys;
  }
  p_ctl_mod->n_keys++;



//---Initializations for cbpm_find_delay_params
  p_key = &(p_ctl_mod->key[p_ctl_mod->n_keys]);
  // configuration
  p_key->p_config      = &(cbpm_find_delay_params_cfg);
  //data pointers
  p_key->data.ptr[ 0]  = (void *)(&(p_data->cbpm_find_delay_params.hist_index));
  p_key->data.ptr[ 1]  = (void *)(&(p_data->cbpm_find_delay_params.use_data_enable));
  // tag2key_map
  first_tag = p_key->p_config->struct_tag;
  num_tags  = p_key->p_config->num_pkts;
  for (tag = first_tag; tag < (first_tag + num_tags); tag++) {
    p_ctl_mod->tag2key_map[tag] = p_ctl_mod->n_keys;
  }
  p_ctl_mod->n_keys++;



//---Initializations for cbpm_chan_cal_work
  p_key = &(p_ctl_mod->key[p_ctl_mod->n_keys]);
  // configuration
  p_key->p_config      = &(cbpm_chan_cal_work_cfg);
  //data pointers
  p_key->data.ptr[ 0]  = (void *)(&(p_data->cbpm_chan_cal_work.chan_cal_data[0]));
  // tag2key_map
  first_tag = p_key->p_config->struct_tag;
  num_tags  = p_key->p_config->num_pkts;
  for (tag = first_tag; tag < (first_tag + num_tags); tag++) {
    p_ctl_mod->tag2key_map[tag] = p_ctl_mod->n_keys;
  }
  p_ctl_mod->n_keys++;



//---Initializations for cbpm_ped_cal_out
  p_key = &(p_ctl_mod->key[p_ctl_mod->n_keys]);
  // configuration
  p_key->p_config      = &(cbpm_ped_cal_out_cfg);
  //data pointers
  p_key->data.ptr[ 0]  = (void *)(&(p_data->cbpm_ped_cal_out.ped_table[0][0][0]));
  p_key->data.ptr[ 1]  = (void *)(&(p_data->cbpm_ped_cal_out.ped_rms_table[0][0][0]));
  // tag2key_map
  first_tag = p_key->p_config->struct_tag;
  num_tags  = p_key->p_config->num_pkts;
  for (tag = first_tag; tag < (first_tag + num_tags); tag++) {
    p_ctl_mod->tag2key_map[tag] = p_ctl_mod->n_keys;
  }
  p_ctl_mod->n_keys++;



//---Initializations for cbpm_raw_params
  p_key = &(p_ctl_mod->key[p_ctl_mod->n_keys]);
  // configuration
  p_key->p_config      = &(cbpm_raw_params_cfg);
  //data pointers
  p_key->data.ptr[ 0]  = (void *)(&(p_data->cbpm_raw_params.num_turns));
  p_key->data.ptr[ 1]  = (void *)(&(p_data->cbpm_raw_params.scale_mode));
  p_key->data.ptr[ 2]  = (void *)(&(p_data->cbpm_raw_params.trig_turns_delay));
  p_key->data.ptr[ 3]  = (void *)(&(p_data->cbpm_raw_params.spacex_turn));
  p_key->data.ptr[ 4]  = (void *)(&(p_data->cbpm_raw_params.use_data_enable));
  p_key->data.ptr[ 5]  = (void *)(&(p_data->cbpm_raw_params.trig_mask));
  p_key->data.ptr[ 6]  = (void *)(&(p_data->cbpm_raw_params.phase_race_wait));
  // tag2key_map
  first_tag = p_key->p_config->struct_tag;
  num_tags  = p_key->p_config->num_pkts;
  for (tag = first_tag; tag < (first_tag + num_tags); tag++) {
    p_ctl_mod->tag2key_map[tag] = p_ctl_mod->n_keys;
  }
  p_ctl_mod->n_keys++;



//---Initializations for cbpm_proc_params
  p_key = &(p_ctl_mod->key[p_ctl_mod->n_keys]);
  // configuration
  p_key->p_config      = &(cbpm_proc_params_cfg);
  //data pointers
  p_key->data.ptr[ 0]  = (void *)(&(p_data->cbpm_proc_params.avg_mode));
  // tag2key_map
  first_tag = p_key->p_config->struct_tag;
  num_tags  = p_key->p_config->num_pkts;
  for (tag = first_tag; tag < (first_tag + num_tags); tag++) {
    p_ctl_mod->tag2key_map[tag] = p_ctl_mod->n_keys;
  }
  p_ctl_mod->n_keys++;



//---Initializations for cbpm_cal_params
  p_key = &(p_ctl_mod->key[p_ctl_mod->n_keys]);
  // configuration
  p_key->p_config      = &(cbpm_cal_params_cfg);
  //data pointers
  p_key->data.ptr[ 0]  = (void *)(&(p_data->cbpm_cal_params.delay_cal));
  p_key->data.ptr[ 1]  = (void *)(&(p_data->cbpm_cal_params.gain_cal));
  p_key->data.ptr[ 2]  = (void *)(&(p_data->cbpm_cal_params.delay_init));
  p_key->data.ptr[ 3]  = (void *)(&(p_data->cbpm_cal_params.gain_xcal));
  // tag2key_map
  first_tag = p_key->p_config->struct_tag;
  num_tags  = p_key->p_config->num_pkts;
  for (tag = first_tag; tag < (first_tag + num_tags); tag++) {
    p_ctl_mod->tag2key_map[tag] = p_ctl_mod->n_keys;
  }
  p_ctl_mod->n_keys++;



//---Initializations for cbpm_diagnostic
  p_key = &(p_ctl_mod->key[p_ctl_mod->n_keys]);
  // configuration
  p_key->p_config      = &(cbpm_diagnostic_cfg);
  //data pointers
  p_key->data.ptr[ 0]  = (void *)(&(p_data->cbpm_diagnostic.pre_pf_peak_block_delays[0]));
  p_key->data.ptr[ 1]  = (void *)(&(p_data->cbpm_diagnostic.pre_pf_offset_chan_delays[0]));
  p_key->data.ptr[ 2]  = (void *)(&(p_data->cbpm_diagnostic.scrub_value));
  p_key->data.ptr[ 3]  = (void *)(&(p_data->cbpm_diagnostic.sample_at_zero_crossing));
  p_key->data.ptr[ 4]  = (void *)(&(p_data->cbpm_diagnostic.magic_wait_calibration_value));
  p_key->data.ptr[ 5]  = (void *)(&(p_data->cbpm_diagnostic.test_step_index));
  // tag2key_map
  first_tag = p_key->p_config->struct_tag;
  num_tags  = p_key->p_config->num_pkts;
  for (tag = first_tag; tag < (first_tag + num_tags); tag++) {
    p_ctl_mod->tag2key_map[tag] = p_ctl_mod->n_keys;
  }
  p_ctl_mod->n_keys++;



//---Initializations for cbpm_code_params
  p_key = &(p_ctl_mod->key[p_ctl_mod->n_keys]);
  // configuration
  p_key->p_config      = &(cbpm_code_params_cfg);
  //data pointers
  p_key->data.ptr[ 0]  = (void *)(&(p_data->cbpm_code_params.tests[0]));
  p_key->data.ptr[ 1]  = (void *)(&(p_data->cbpm_code_params.execution_flags[0]));
  // tag2key_map
  first_tag = p_key->p_config->struct_tag;
  num_tags  = p_key->p_config->num_pkts;
  for (tag = first_tag; tag < (first_tag + num_tags); tag++) {
    p_ctl_mod->tag2key_map[tag] = p_ctl_mod->n_keys;
  }
  p_ctl_mod->n_keys++;



//---Initializations for cbpm_test_results
  p_key = &(p_ctl_mod->key[p_ctl_mod->n_keys]);
  // configuration
  p_key->p_config      = &(cbpm_test_results_cfg);
  //data pointers
  p_key->data.ptr[ 0]  = (void *)(&(p_data->cbpm_test_results.EncodedStatus[0]));
  p_key->data.ptr[ 1]  = (void *)(&(p_data->cbpm_test_results.Statuses[0][0]));
  // tag2key_map
  first_tag = p_key->p_config->struct_tag;
  num_tags  = p_key->p_config->num_pkts;
  for (tag = first_tag; tag < (first_tag + num_tags); tag++) {
    p_ctl_mod->tag2key_map[tag] = p_ctl_mod->n_keys;
  }
  p_ctl_mod->n_keys++;



//---Initializations for cbpm_btest_results
  p_key = &(p_ctl_mod->key[p_ctl_mod->n_keys]);
  // configuration
  p_key->p_config      = &(cbpm_btest_results_cfg);
  //data pointers
  p_key->data.ptr[ 0]  = (void *)(&(p_data->cbpm_btest_results.Statuseshist[0][0][0]));
  p_key->data.ptr[ 1]  = (void *)(&(p_data->cbpm_btest_results.StatusVals[0][0][0]));
  p_key->data.ptr[ 2]  = (void *)(&(p_data->cbpm_btest_results.statushist[0]));
  // tag2key_map
  first_tag = p_key->p_config->struct_tag;
  num_tags  = p_key->p_config->num_pkts;
  for (tag = first_tag; tag < (first_tag + num_tags); tag++) {
    p_ctl_mod->tag2key_map[tag] = p_ctl_mod->n_keys;
  }
  p_ctl_mod->n_keys++;



  return F_SUCCESS;
}
