//------------------------------------------------------------------------
//  D O     N O T     E D I T     T H I S     F I L E
//------------------------------------------------------------------------
// File         :  cbpm_pkt_tables_a.h
// Date Created :  Fri Sep 14 14:08:01 2012
//
// Description  : This file was automatically generated by the BIParser.
//                It provides packet address table and packet size table
//                initialization code as well as an instrument memory
//                usage summary for the communication data structures.
//------------------------------------------------------------------------


//-----------------------------------------------------------------------+
//  The following provides for C++ compatibility (ie, C++ routines can   |
//  explicitly use this include file).                                   |
//-----------------------------------------------------------------------+
#if defined (__cplusplus)
extern "C" {
#endif


// System
#include <defts101.h>
// Core
#include "dig_board_6048-113.h"
#include "cbi_core_inst_includes.h"
//Local
#include "cbpm_tags_a.h"
#include "cbpm_commstructs_a.h"
#include "cbpm_system.h"

#include "cbpm_trace.h"

//==================================================================================
// Memory usage for communication data structures:
//
// Structure           Element tally                             Mem (words)  # X-Pkts 
//==================================================================================
// cbpm_cmd_params     : (18 + 40 + 640)                               = 698    349
// cbpm_temperatures   : (2 + 4)                                       = 6      1
// cbpm_timing_config  : (6 * (2 + 2 + 2 + 2 + 2*4))                   = 96     1
// cbpm_gain_config    : (11 + 2*4*11 + 2*4*11 + 4)                    = 191    1
// cbpm_pedestal_config: (3 * (2*4*11 + 2*4*11))                       = 528    3
// cbpm_op_timing      : (1)                                           = 1      1
// cbpm_op_gain        : (4*2)                                         = 8      1
// cbpm_raw_data_header: (7 + 2 + 2 + 4 + 4 + 4 + 4 + 4 + 4*2)         = 39     1
// cbpm_adc_buffer0    : (327680)                                      = 327680 1280
// cbpm_adc_buffer1    : (327680)                                      = 327680 1280
// cbpm_adc_buffer2    : (327680)                                      = 327680 1280
// cbpm_adc_buffer3    : (327680)                                      = 327680 1280
// cbpm_adc_buffer4    : (327680)                                      = 327680 1280
// cbpm_adc_buffer5    : (327680)                                      = 327680 1280
// cbpm_adc_buffer6    : (327680)                                      = 327680 1280
// cbpm_adc_buffer7    : (327680)                                      = 327680 1280
// cbpm_ph_word_buf    : (327680)                                      = 327680 1280
// cbpm_proc_buf       : (640 * (3 + 4 + 4))                           = 7040   32
// cbpm_proc_buf_header: (2 + 3)                                       = 5      1
// cbpm_proc_sum_dat_buf: (1 + 640 + 4*2)                               = 649    11
// cbpm_proc_buf_io    : (1)                                           = 1      1
// cbpm_summ_buf       : (640 * (2 + 4 + 4))                           = 6400   25
// cbpm_signal_stat    : (4 + 4)                                       = 8      1
// cbpm_phase_config   : (2*3 + (2)*(3+1) + (2)*(3+1))                 = 22     1
// cbpm_beta_phase_out : (3 + 5*2*2*2*4 + 4)                           = 167    1
// cbpm_find_delay_out : (3 + 12 + 4 + 4 + 4 + 4)                      = 31     1
// cbpm_bfind_delay_out: (8*4 + 8*4 + 8*4 + 8 + 8 + 8)                 = 120    1
// cbpm_find_delay_params: (2)                                           = 2      1
// cbpm_chan_cal_work  : (4 * (1024 + 1024))                           = 8192   32
// cbpm_ped_cal_out    : (2*4*11 + 2*4*11)                             = 176    1
// cbpm_raw_params     : (7)                                           = 7      1
// cbpm_proc_params    : (1)                                           = 1      1
// cbpm_cal_params     : (4)                                           = 4      1
// cbpm_diagnostic     : (4 + 4 + 4)                                   = 12     1
// cbpm_code_params    : (6 * (5) + 20)                                = 50     1
// cbpm_test_results   : (6 + 6*4)                                     = 30     1
// cbpm_btest_results  : (8*6*4 + 8*6*4 + 8)                           = 392    2
//                                                           -----------------------
//                                                            TOTAL : 2973996
//==================================================================================


int init_packet_tables() {
   //-------------------------------------------------------+
   // Packet address table initialization                   |
   //-------------------------------------------------------+
   *(p_pkt_adr_table + CBPM_CMD_PARAMS_TAG)             = (int)&INST_cmd_params     + CBI_MPS_OFFSET;
   *(p_pkt_adr_table + CBPM_TEMPERATURES_TAG)           = (int)&INST_temperatures   + CBI_MPS_OFFSET;
   *(p_pkt_adr_table + CBPM_TIMING_CONFIG_TAG)          = (int)&INST_timing_config  + CBI_MPS_OFFSET;
   *(p_pkt_adr_table + CBPM_GAIN_CONFIG_TAG)            = (int)&INST_gain_config    + CBI_MPS_OFFSET;
   *(p_pkt_adr_table + CBPM_PEDESTAL_CONFIG_TAG)        = (int)&INST_pedestal_config + CBI_MPS_OFFSET;
   *(p_pkt_adr_table + CBPM_OP_TIMING_TAG)              = (int)&INST_op_timing      + CBI_MPS_OFFSET;
   *(p_pkt_adr_table + CBPM_OP_GAIN_TAG)                = (int)&INST_op_gain        + CBI_MPS_OFFSET;
   *(p_pkt_adr_table + CBPM_RAW_DATA_HEADER_TAG)        = (int)&INST_raw_data_header + CBI_MPS_OFFSET;
   *(p_pkt_adr_table + CBPM_ADC_BUFFER0_TAG)            = (int)&INST_adc_buffer0    + CBI_MPS_OFFSET;
   *(p_pkt_adr_table + CBPM_ADC_BUFFER1_TAG)            = (int)&INST_adc_buffer1    + CBI_MPS_OFFSET;
   *(p_pkt_adr_table + CBPM_ADC_BUFFER2_TAG)            = (int)&INST_adc_buffer2    + CBI_MPS_OFFSET;
   *(p_pkt_adr_table + CBPM_ADC_BUFFER3_TAG)            = (int)&INST_adc_buffer3    + CBI_MPS_OFFSET;
   *(p_pkt_adr_table + CBPM_ADC_BUFFER4_TAG)            = (int)&INST_adc_buffer4    + CBI_MPS_OFFSET;
   *(p_pkt_adr_table + CBPM_ADC_BUFFER5_TAG)            = (int)&INST_adc_buffer5    + CBI_MPS_OFFSET;
   *(p_pkt_adr_table + CBPM_ADC_BUFFER6_TAG)            = (int)&INST_adc_buffer6    + CBI_MPS_OFFSET;
   *(p_pkt_adr_table + CBPM_ADC_BUFFER7_TAG)            = (int)&INST_adc_buffer7    + CBI_MPS_OFFSET;
   *(p_pkt_adr_table + CBPM_PH_WORD_BUF_TAG)            = (int)&INST_ph_word_buf   ;
   *(p_pkt_adr_table + CBPM_PROC_BUF_TAG)               = (int)&INST_proc_buf      ;
   *(p_pkt_adr_table + CBPM_PROC_BUF_HEADER_TAG)        = (int)&INST_proc_buf_header + CBI_MPS_OFFSET;
   *(p_pkt_adr_table + CBPM_PROC_SUM_DAT_BUF_TAG)       = (int)&INST_proc_sum_dat_buf + CBI_MPS_OFFSET;
   *(p_pkt_adr_table + CBPM_PROC_BUF_IO_TAG)            = (int)&INST_proc_buf_io    + CBI_MPS_OFFSET;
   *(p_pkt_adr_table + CBPM_SUMM_BUF_TAG)               = (int)&INST_summ_buf       + CBI_MPS_OFFSET;
   *(p_pkt_adr_table + CBPM_SIGNAL_STAT_TAG)            = (int)&INST_signal_stat    + CBI_MPS_OFFSET;
   *(p_pkt_adr_table + CBPM_PHASE_CONFIG_TAG)           = (int)&INST_phase_config   + CBI_MPS_OFFSET;
   *(p_pkt_adr_table + CBPM_BETA_PHASE_OUT_TAG)         = (int)&INST_beta_phase_out + CBI_MPS_OFFSET;
   *(p_pkt_adr_table + CBPM_FIND_DELAY_OUT_TAG)         = (int)&INST_find_delay_out + CBI_MPS_OFFSET;
   *(p_pkt_adr_table + CBPM_BFIND_DELAY_OUT_TAG)        = (int)&INST_bfind_delay_out + CBI_MPS_OFFSET;
   *(p_pkt_adr_table + CBPM_FIND_DELAY_PARAMS_TAG)      = (int)&INST_find_delay_params + CBI_MPS_OFFSET;
   *(p_pkt_adr_table + CBPM_CHAN_CAL_WORK_TAG)          = (int)&INST_chan_cal_work  + CBI_MPS_OFFSET;
   *(p_pkt_adr_table + CBPM_PED_CAL_OUT_TAG)            = (int)&INST_ped_cal_out    + CBI_MPS_OFFSET;
   *(p_pkt_adr_table + CBPM_RAW_PARAMS_TAG)             = (int)&INST_raw_params     + CBI_MPS_OFFSET;
   *(p_pkt_adr_table + CBPM_PROC_PARAMS_TAG)            = (int)&INST_proc_params    + CBI_MPS_OFFSET;
   *(p_pkt_adr_table + CBPM_CAL_PARAMS_TAG)             = (int)&INST_cal_params     + CBI_MPS_OFFSET;
   *(p_pkt_adr_table + CBPM_DIAGNOSTIC_TAG)             = (int)&INST_diagnostic     + CBI_MPS_OFFSET;
   *(p_pkt_adr_table + CBPM_CODE_PARAMS_TAG)            = (int)&INST_code_params    + CBI_MPS_OFFSET;
   *(p_pkt_adr_table + CBPM_TEST_RESULTS_TAG)           = (int)&INST_test_results   + CBI_MPS_OFFSET;
   *(p_pkt_adr_table + CBPM_BTEST_RESULTS_TAG)          = (int)&INST_btest_results  + CBI_MPS_OFFSET;
   //-------------------------------------------------------+
   // Packet size table initialization                      |
   //-------------------------------------------------------+
   *(p_pkt_siz_table + CBPM_CMD_PARAMS_TAG)             = 2;
   *(p_pkt_siz_table + CBPM_TEMPERATURES_TAG)           = sizeof(INST_temperatures);
   *(p_pkt_siz_table + CBPM_TIMING_CONFIG_TAG)          = sizeof(INST_timing_config);
   *(p_pkt_siz_table + CBPM_GAIN_CONFIG_TAG)            = sizeof(INST_gain_config); 
   *(p_pkt_siz_table + CBPM_PEDESTAL_CONFIG_TAG)        = 176;
   *(p_pkt_siz_table + CBPM_OP_TIMING_TAG)              = sizeof(INST_op_timing);   
   *(p_pkt_siz_table + CBPM_OP_GAIN_TAG)                = sizeof(INST_op_gain);     
   *(p_pkt_siz_table + CBPM_RAW_DATA_HEADER_TAG)        = sizeof(INST_raw_data_header);
   *(p_pkt_siz_table + CBPM_ADC_BUFFER0_TAG)            = 256;
   *(p_pkt_siz_table + CBPM_ADC_BUFFER1_TAG)            = 256;
   *(p_pkt_siz_table + CBPM_ADC_BUFFER2_TAG)            = 256;
   *(p_pkt_siz_table + CBPM_ADC_BUFFER3_TAG)            = 256;
   *(p_pkt_siz_table + CBPM_ADC_BUFFER4_TAG)            = 256;
   *(p_pkt_siz_table + CBPM_ADC_BUFFER5_TAG)            = 256;
   *(p_pkt_siz_table + CBPM_ADC_BUFFER6_TAG)            = 256;
   *(p_pkt_siz_table + CBPM_ADC_BUFFER7_TAG)            = 256;
   *(p_pkt_siz_table + CBPM_PH_WORD_BUF_TAG)            = 256;
   *(p_pkt_siz_table + CBPM_PROC_BUF_TAG)               = 220;
   *(p_pkt_siz_table + CBPM_PROC_BUF_HEADER_TAG)        = sizeof(INST_proc_buf_header);
   *(p_pkt_siz_table + CBPM_PROC_SUM_DAT_BUF_TAG)       = 59;
   *(p_pkt_siz_table + CBPM_PROC_BUF_IO_TAG)            = sizeof(INST_proc_buf_io); 
   *(p_pkt_siz_table + CBPM_SUMM_BUF_TAG)               = 256;
   *(p_pkt_siz_table + CBPM_SIGNAL_STAT_TAG)            = sizeof(INST_signal_stat); 
   *(p_pkt_siz_table + CBPM_PHASE_CONFIG_TAG)           = sizeof(INST_phase_config);
   *(p_pkt_siz_table + CBPM_BETA_PHASE_OUT_TAG)         = sizeof(INST_beta_phase_out);
   *(p_pkt_siz_table + CBPM_FIND_DELAY_OUT_TAG)         = sizeof(INST_find_delay_out);
   *(p_pkt_siz_table + CBPM_BFIND_DELAY_OUT_TAG)        = sizeof(INST_bfind_delay_out);
   *(p_pkt_siz_table + CBPM_FIND_DELAY_PARAMS_TAG)      = sizeof(INST_find_delay_params);
   *(p_pkt_siz_table + CBPM_CHAN_CAL_WORK_TAG)          = 256;
   *(p_pkt_siz_table + CBPM_PED_CAL_OUT_TAG)            = sizeof(INST_ped_cal_out); 
   *(p_pkt_siz_table + CBPM_RAW_PARAMS_TAG)             = sizeof(INST_raw_params);  
   *(p_pkt_siz_table + CBPM_PROC_PARAMS_TAG)            = sizeof(INST_proc_params); 
   *(p_pkt_siz_table + CBPM_CAL_PARAMS_TAG)             = sizeof(INST_cal_params);  
   *(p_pkt_siz_table + CBPM_DIAGNOSTIC_TAG)             = sizeof(INST_diagnostic);  
   *(p_pkt_siz_table + CBPM_CODE_PARAMS_TAG)            = sizeof(INST_code_params); 
   *(p_pkt_siz_table + CBPM_TEST_RESULTS_TAG)           = sizeof(INST_test_results);
   *(p_pkt_siz_table + CBPM_BTEST_RESULTS_TAG)          = 196;

  return CBI_F_SUCCESS;
}
