
#ifndef CBPM_INST_DECS_A_H
#define CBPM_INST_DECS_A_H
//------------------------------------------------------------------------
//  D O     N O T     E D I T     T H I S     F I L E
//------------------------------------------------------------------------
// File         :  cbpm_INST_decs_a.h
// Date Created :  Fri Sep 14 14:08:01 2012
//
// Description  : This file was automatically generated by the BIParser.
//                It contains communications data structure declarations
//                internal to the instrument
//----------------------------------------------------------------------------

#include "cbpm_commstructs_a.h"
//-----------------------------------------------------------------------+
//  The following provides for C++ compatibility (ie, C++ routines can   |
//  explicitly use this include file).                                   |
//-----------------------------------------------------------------------+
#if defined (__cplusplus)
extern "C" {
#endif



// Declare all structures used for communicating with control system.
// Storage space will be allocated by the routine that defines 
// INST_NO_EXTERN.  All other routines will refer to that space.
// Anything that the control system can change must be declared "volatile"
// so that the compiler does not try to optimize it out.

#if defined (INST_NO_EXTERN)

//------------------------------------------------------------------------
// "#pragma align _LONG" instances below are for work-around of
// digital board FPGA bug (c. 9-Oct-2009) affecting CBInet structure
// transfers when structures happen to fall near a particular type of
// address rollover boundary.
//------------------------------------------------------------------------
   #pragma align _LONG
volatile CBPM_CMD_PARAMS                 INST_cmd_params;
   #pragma align _LONG
         CBPM_TEMPERATURES               INST_temperatures;
   #pragma align _LONG
volatile CBPM_TIMING_CONFIG              INST_timing_config;
   #pragma align _LONG
volatile CBPM_GAIN_CONFIG                INST_gain_config;
   #pragma align _LONG
volatile CBPM_PEDESTAL_CONFIG            INST_pedestal_config;
   #pragma align _LONG
volatile CBPM_OP_TIMING                  INST_op_timing;
   #pragma align _LONG
volatile CBPM_OP_GAIN                    INST_op_gain;
   #pragma align _LONG
         CBPM_RAW_DATA_HEADER            INST_raw_data_header;
            CBPM_ADC_BUFFER                 segment("CARD_0_BUF_0") INST_adc_buffer0;
            CBPM_ADC_BUFFER                 segment("CARD_0_BUF_1") INST_adc_buffer1;
            CBPM_ADC_BUFFER                 segment("CARD_1_BUF_0") INST_adc_buffer2;
            CBPM_ADC_BUFFER                 segment("CARD_1_BUF_1") INST_adc_buffer3;
            CBPM_ADC_BUFFER                 segment("CARD_2_BUF_0") INST_adc_buffer4;
            CBPM_ADC_BUFFER                 segment("CARD_2_BUF_1") INST_adc_buffer5;
            CBPM_ADC_BUFFER                 segment("CARD_3_BUF_0") INST_adc_buffer6;
            CBPM_ADC_BUFFER                 segment("CARD_3_BUF_1") INST_adc_buffer7;
            CBPM_PH_WORD_BUF                segment("PHASE_WORD_SEG") INST_ph_word_buf;
            CBPM_PROC_BUF                   segment("PROC_DATA_SEG") INST_proc_buf;
   #pragma align _LONG
         CBPM_PROC_BUF_HEADER            INST_proc_buf_header;
   #pragma align _LONG
         CBPM_PROC_SUM_DAT_BUF           INST_proc_sum_dat_buf;
   #pragma align _LONG
volatile CBPM_PROC_BUF_IO                INST_proc_buf_io;
   #pragma align _LONG
         CBPM_SUMM_BUF                   INST_summ_buf;
   #pragma align _LONG
         CBPM_SIGNAL_STAT                INST_signal_stat;
   #pragma align _LONG
         CBPM_PHASE_CONFIG               INST_phase_config;
   #pragma align _LONG
         CBPM_BETA_PHASE_OUT             INST_beta_phase_out;
   #pragma align _LONG
         CBPM_FIND_DELAY_OUT             INST_find_delay_out;
   #pragma align _LONG
         CBPM_BFIND_DELAY_OUT            INST_bfind_delay_out;
   #pragma align _LONG
volatile CBPM_FIND_DELAY_PARAMS          INST_find_delay_params;
   #pragma align _LONG
         CBPM_CHAN_CAL_WORK              INST_chan_cal_work;
   #pragma align _LONG
         CBPM_PED_CAL_OUT                INST_ped_cal_out;
   #pragma align _LONG
volatile CBPM_RAW_PARAMS                 INST_raw_params;
   #pragma align _LONG
volatile CBPM_PROC_PARAMS                INST_proc_params;
   #pragma align _LONG
volatile CBPM_CAL_PARAMS                 INST_cal_params;
   #pragma align _LONG
volatile CBPM_DIAGNOSTIC                 INST_diagnostic;
   #pragma align _LONG
volatile CBPM_CODE_PARAMS                INST_code_params;
   #pragma align _LONG
         CBPM_TEST_RESULTS               INST_test_results;
   #pragma align _LONG
         CBPM_BTEST_RESULTS              INST_btest_results;


#else
   volatile extern CBPM_CMD_PARAMS                 INST_cmd_params;
            extern CBPM_TEMPERATURES               INST_temperatures;
   volatile extern CBPM_TIMING_CONFIG              INST_timing_config;
   volatile extern CBPM_GAIN_CONFIG                INST_gain_config;
   volatile extern CBPM_PEDESTAL_CONFIG            INST_pedestal_config;
   volatile extern CBPM_OP_TIMING                  INST_op_timing;
   volatile extern CBPM_OP_GAIN                    INST_op_gain;
            extern CBPM_RAW_DATA_HEADER            INST_raw_data_header;
            extern CBPM_ADC_BUFFER                 segment("CARD_0_BUF_0") INST_adc_buffer0;
            extern CBPM_ADC_BUFFER                 segment("CARD_0_BUF_1") INST_adc_buffer1;
            extern CBPM_ADC_BUFFER                 segment("CARD_1_BUF_0") INST_adc_buffer2;
            extern CBPM_ADC_BUFFER                 segment("CARD_1_BUF_1") INST_adc_buffer3;
            extern CBPM_ADC_BUFFER                 segment("CARD_2_BUF_0") INST_adc_buffer4;
            extern CBPM_ADC_BUFFER                 segment("CARD_2_BUF_1") INST_adc_buffer5;
            extern CBPM_ADC_BUFFER                 segment("CARD_3_BUF_0") INST_adc_buffer6;
            extern CBPM_ADC_BUFFER                 segment("CARD_3_BUF_1") INST_adc_buffer7;
            extern CBPM_PH_WORD_BUF                segment("PHASE_WORD_SEG") INST_ph_word_buf;
            extern CBPM_PROC_BUF                   segment("PROC_DATA_SEG") INST_proc_buf;
            extern CBPM_PROC_BUF_HEADER            INST_proc_buf_header;
            extern CBPM_PROC_SUM_DAT_BUF           INST_proc_sum_dat_buf;
   volatile extern CBPM_PROC_BUF_IO                INST_proc_buf_io;
            extern CBPM_SUMM_BUF                   INST_summ_buf;
            extern CBPM_SIGNAL_STAT                INST_signal_stat;
            extern CBPM_PHASE_CONFIG               INST_phase_config;
            extern CBPM_BETA_PHASE_OUT             INST_beta_phase_out;
            extern CBPM_FIND_DELAY_OUT             INST_find_delay_out;
            extern CBPM_BFIND_DELAY_OUT            INST_bfind_delay_out;
   volatile extern CBPM_FIND_DELAY_PARAMS          INST_find_delay_params;
            extern CBPM_CHAN_CAL_WORK              INST_chan_cal_work;
            extern CBPM_PED_CAL_OUT                INST_ped_cal_out;
   volatile extern CBPM_RAW_PARAMS                 INST_raw_params;
   volatile extern CBPM_PROC_PARAMS                INST_proc_params;
   volatile extern CBPM_CAL_PARAMS                 INST_cal_params;
   volatile extern CBPM_DIAGNOSTIC                 INST_diagnostic;
   volatile extern CBPM_CODE_PARAMS                INST_code_params;
            extern CBPM_TEST_RESULTS               INST_test_results;
            extern CBPM_BTEST_RESULTS              INST_btest_results;


#endif //(..._NO_EXTERN)

#if defined (__cplusplus)
}
#endif



#endif // INST_..._H
