//------------------------------------------------------------------------
//  D O     N O T     E D I T     T H I S     F I L E
//------------------------------------------------------------------------
// File         :  CBPM_protos_a.h
// Date Created :  Tue Apr 17 16:49:54 2012
//
// Description  : This file was automatically generated by the BIParser.
//                It contains C prototypes for the custom datatype conversion
//                functions that were generated for derived typedefs.
//----------------------------------------------------------------------------
#ifndef CBPM_protos_A_H
#define CBPM_protos_A_H
int cbpm_init_a(CBI_CTL_MODULE*);

int *cbpm_tsetup_convert(int, int*, int, int, int, void*);
int *cbpm_pedestals_convert(int, int*, int, int, int, void*);
int *cbpm_tscan_data_convert(int, int*, int, int, int, void*);
int *cbpm_proc_data_convert(int, int*, int, int, int, void*);
int *cbpm_summ_data_convert(int, int*, int, int, int, void*);
int *cbpm_chan_cal_data_convert(int, int*, int, int, int, void*);
int *cbpm_test_params_struct_convert(int, int*, int, int, int, void*);
#endif
