#!/bin/bash

#Run this script from ../../CBIC like this:
#../CBPM-TSHARC/tools/session_autoscripts/INPUT_proc_data Custom:mgs9-first

echo $1
../bin/cbic -t -a $1 <<EOF
5

1
-1
a

n
n
n


36
EOF
echo "Ran Process Data."
echo ""
